services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 853:853/tcp # TLS dns over tcp
      - 853:853/udp # TLS dns over udp
      - 3001:3001/tcp # initial setup web interface
    volumes:
      - config:/opt/adguardhome/conf # app configuration
      - work:/opt/adguardhome/work # app working directory
    networks:
      - proxy-network

volumes:
  config:
    driver: local
  work:
    driver: local