services:
  app:
    container_name: gatitasbordando-pos
    build:
      context: ../gatitasbordando-pos
      dockerfile: ../gatitasbordando-pos/Dockerfile
    networks:
      - proxy-network
    env_file:
      - .env
    volumes:
      - .:/app
    command: deno run -A main.ts