services:
  tailscale: 
    container_name: tailscale 
    #hostname: tailscale-nas 
    image: tailscale/tailscale:stable
    network_mode: "service:nginx_proxy_manager"
    env_file:
    - .env
    environment:
    - TS_AUTHKEY=${TS_AUTHKEY}
    - TS_EXTRA_ARGS=--advertise-tags=tag:container
    - TS_STATE_DIR=/var/lib/tailscale
    - TS_USERSPACE=false
    #- TS_ACCEPT_DNS=false
    - TS_ROUTES=192.168.0.0/24
    #- TS_SERVE_CONFIG=./config/homeassistant.json
    volumes: 
      - ./tailscale:/var/lib/tailscale # State data will be stored in this directory 
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work 
    cap_add: # Required for tailscale to work 
      - net_admin 
      - sys_module
    restart: unless-stopped